Add method for simplification common test cases
keboola/datadir-tests pull request #12
Opened 2018-09-13 20:47 UTC by Actimel

The new method should simplify most of test cases. I started using it here (https://github.com/keboola/db-extractor-common/blob/david-improve-tests/tests/Functional/DatadirTest.php) and consider it might be handy to have implemented in datadir-tests.

Mabe we should figure out better method name.

2018-09-13 22:00 UTC, odinuv commented
proc ne, koukam, ze by se to dalo pohodlne pouzit i ve wr-slack a matne mam pocit, ze me neco takovyho tam napadalo, jmeno je blby, ale lepsi me nenapada :)

misto json_encode pouzit \GuzzleHttp\json_encode nebo overit navratovou hodnotu - u testu se obcas stava, ze tam clovek posle nejakej garbage a melo by to zavcas vyletet

2018-09-14 08:46 UTC, tomasfejfar commented
Nebylo by lepší:
```
$this->runTestWithCustomConfiguration(DatadirTestSpecification $specification, array $customConfiguration)
```

Nebo ještě lépe udělat CustomConfigDatadirTestSpecification a metodu, která přijímá jen ten a tahá si z něj tu konfiguraci? Cílem by mělo být co nějvětší reuse té existující metody. Pokud to třeba nedostačuje, tak by se dala dál rozdělit a přidat ji nějaké hooky. Velká část věcí, která je teď dělaná v těch custom implementacích testů by se dala IMO udělat v setUp() metodě. Pokud se testy nazájem liší v tom, co by měly mít v setUp metodě, tak můžou být v různých TestCase třídách... 

Úplně se mi nezdá to obcházení té specification a dávání ji tam úplně na poslední chvíli, když už ji vyžaduje typehint a všude předtím do té doby tahat skaláry. 

Jak to chápu já, tak jediný scénář, který je teď problém je podstrčení vlastního configu. Db jde řešit v setUp, ale config se dá uložit až potom co je jasný tempdir. Takže by třeba mohl být řešením fakt to, že tam jen přibude metoda, která z Specification vytahne config a použije na něj třeba closure, kterou dostane. Nebo prostě jen zapíše config, který si ze sepecification vytahne. 

Případně by se to dalo udělat tak, že by ten "tempdir" byl nějak deterministický (tj. temp per TestCase třeba), aby se do něj dalo zapsat ještě před tím, než na to nastoupí ten samotný testDatadir(), který ho teď vytváří.

2018-09-14 08:58 UTC, odinuv commented
afaik se testy lisi prave v tom setupu predtim testem, a mit kazdy test v jine tride? no tak to je lepsi nechat jak je to ted :)

deterministicky tempdir taky ne, s tim jsme se uz mockrat spalili (proto vznikla ta Temp trida)

2018-09-14 09:07 UTC, odinuv commented
ja jsem to, co navrhuje david bral proste jako syntactic sugar, ktery je nice to have, nevim jestli je prinosny to predelavat na closures aby se to "zjednodusilo"

2018-09-17 11:58 UTC, tomasfejfar commented
Tak za mě aspoň přejmenovat na `*WithCustomConfiguration` nbo `withForcedConfiguration` nebo `withInjectedConfiguration`. Aby bylo jasné, proč se to takhle dělá. Protože to není "běžný" (common) způsob spouštění, ale spíš "pokročilý" (advanced)...

2018-09-17 11:59 UTC, tomasfejfar requested changes
Tak za mě prosím přejmenovat na `withCustomConfiguration` (nebo Forced, nebo Injected). Tohle totiž není "common" (běžný) use case. Je to spíš "advanced" nebo "custom"...

2018-09-17 13:36 UTC, Actimel commented
@tomasfejfar takze `runCommonTestWithCustomConfiguration` je za tebe ok?

2018-09-17 14:17 UTC, tomasfejfar commented
Akorát myslím, že tam nemusí být to "common", ale jo.

2018-09-17 15:02 UTC, tomasfejfar approved these changes

2018-09-17 15:15 UTC, merged